### ISSUE TITLE
cuda() takes at most 2 arguments(3 given)

### ISSUE THREAD

**Issue by wendyWeng** [silverneko/multi-sepconv-interp#1] opened 2018-05-18 02:58 UTC
when I run the train.py, I get the error

**Comment by silverneko** [comment] 2018-05-18 06:45
Can you give a complete error log?

By the way, even though I tried to implement the paper's model, my training process wasn't successful. I don't know if the problem is with my implementation or with my dataset though.

**Comment by wendyWeng** [comment] 2018-05-18 07:06
Traceback (most recent call last):
  File "train.py", line 331, in <module>
    main()
  File "train.py", line 225, in main
    train(training_data_loader, optimizer, model, loss, epoch)
  File "train.py", line 251, in train
    loss_var = loss(output[:, :, 25:-25, 25:-25], target[:, :, 25:-25, 25:-25])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/loss.py", line 61, in forward
    return F.l1_loss(input, target, size_average=self.size_average)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 815, in l1_loss
    return _functions.thnn.L1Loss.apply(input, target, size_average)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/thnn/auto.py", line 47, in forward
    output, *ctx.additional_args)
TypeError: FloatAbsCriterion_updateOutput received an invalid combination of arguments - got (int, torch.FloatTensor, torch.cuda.FloatTensor, torch.FloatTensor, bool), but expected (int state, torch.FloatTensor input, torch.FloatTensor target, torch.FloatTensor output, bool sizeAverage)

**Comment by wendyWeng** [comment] 2018-05-18 07:12
Thanks! I run it once more, and get another erorr. My train set consists of 23 pairs left-right view, different from the papers'.

**Comment by silverneko** [comment] 2018-05-18 07:49
I guess you may be mixing cpu tensors and gpu tensors. Arguments of a tensor operation has to be of the same device. Either all arguments should be cpu tensors or be gpu tensors. I advise you double check your code.

**Comment by wendyWeng** [comment] 2018-05-18 07:55
But I have checked my code, all tensors are gpu tensors. 
def main():
    print("===> Loading datasets")
    train_set = DatasetFromHdf5("/data/whm/0325/trainx2.h5")
    training_data_loader = DataLoader(dataset=train_set, num_workers = 1, batch_size=1, shuffle = False)
    
    print("===> Building model")
    model = Network().cuda()
    
    print("===> Setting GPU")

    loss = torch.nn.L1Loss().cuda() 
    

    print("===> load lf model")
    model_dict = model.state_dict()
    pretrained_dict = torch.load('./network-' + arguments_strModel + '.pytorch')
    keys = []
    for k, v in pretrained_dict.items():
        keys.append(k)
    i = 0
    for k, v in model_dict.items():
        if v.size() == pretrained_dict[keys[i]].size():
            print(k, ',', keys[i])
            model_dict[k] = pretrained_dict[keys[i]]
            i = i + 1
    model.load_state_dict(model_dict)
    
    print("===> Setting Optimizer")
    optimizer = torch.optim.Adamax(model.parameters(), lr=1e-3, betas=(0.9, 0.999), eps=1e-8, weight_decay=0)

    print("===> Training")
    start_epoch = 1
    epoch = 50
    for epoch in range(start_epoch, start_epoch + epoch):
        train(training_data_loader, optimizer, model, loss, epoch)
        filename = 'model-'+str(epoch).rjust(3, '0')
        save_model(epoch, model, optimizer, filename)
        
def train(training_data_loader, optimizer, model, loss, epoch):
    
    subbatch_count = int(batch_size / subbatch_size)
    batch_count = int(np.ceil(len(training_data_loader) / subbatch_count))
    batch_i = 0
    train_loss = AverageMeter('Loss')
    batch_time = AverageMeter('Batch Time')
    subbatch_loss = 0
    subbatch_loss_n = 0
    subbatch_time = 0
    batch_time_end = elapse_time = time.time()
    
    model.train()

    for iteration, batch in enumerate(training_data_loader, 1):
        input1, input2, target = Variable(batch[0]), Variable(batch[1]), Variable(batch[2])
        input1 = input1.cuda()
        input2 = input2.cuda()  
        target = target.cuda()
        
        output = model(input1, input2)
        
        loss_var = loss(output[:, :, 25:-25, 25:-25], target[:, :, 25:-25, 25:-25])
        loss_var = loss_var / subbatch_count

**Comment by silverneko** [comment] 2018-05-18 08:12
I just looked up pytorch's document and I'm surprised to find out that the APIs of torch.Tensor and torch.autograd.Variable have merged. Maybe your problem has something to do with the API change?

**Comment by silverneko** [comment] 2018-05-18 08:21
I honestly don't know what is causing your problem. Maybe try to assert / print the type of input1,input2,target,output after each step and check if the types of the tensors are consistent?

**Comment by wendyWeng** [comment] 2018-05-19 01:21
You are right, it's caused by the version of pytorch. Just upgrade pytorch to 0.4.0 version to solve this problem.

**Closed as completed** 2018-05-27 07:16 UTC
